### ISSUE TITLE
Поправить код

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-nxt#10]
Этот код надо поправить:

```
app.get('/user', (req, res) => {
  console.log(req.user);
  req.isAuthenticated() ?
    res.json(req.user)
    :
    res.json({ success: false });
});
```

Во-первых, мы придерживаемся схемы, что все рест поинты у нас идут с путем `/api/v1...`.

Во-вторых, что будет если объект user вдруг будет включать в себя поле success? Ваш код успешную авториацию сессии распознает как результат неуспешной авторизации.

И в случае успеха и в случае неуспеха надо возвращать объект одной и той же структуры. Причем желательно не плодить лишних типов. Поэтому логично расширить тип `IAuthResult`, добавив в него `user?: Express.User` если он действительно нужен на клиенте. Если не нужен, то не надо его передавать.

**Comment by sashazernin** [comment]
IAuthResult используется на другом эндпоинте (не додходит для этого эндпоинта) поэтому возвращаю просто объект одной и тожей структуры.
