### ISSUE TITLE
Сделки. Поиск

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#114]
Организовать поиск в Сделках (на всех этапах)
Для старта по полям:
- Номер Заявки
- Клиент
- Подразделение

**Comment by hirurg-lybitel** [comment]
![image](https://user-images.githubusercontent.com/11502258/204562106-18c2d319-be4c-4ebe-9f9a-025ef174cddf.png)

**Comment by hirurg-lybitel** [comment]
@hjamesgs гуд?
