### ISSUE TITLE
Уведомления

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#115]
Какую информацию должны отображать уведомления?

- [x] модуль уведомлений
- [x] истекающий срок сделки (сегодня/завтра/просрочено/без срока)
- [x] истекающий срок задачи по сделке (сегодня/завтра/просрочено/без срока)
- [x] сообщения от администратора
- [x] системная информация о новых фичах после обновления

**Comment by hirurg-lybitel** [comment]
@hjamesgs гуд?

**Comment by hjamesgs** [comment]
Уведомления должны учитывать данные и в сделке и по задачам в данной сделке.
Сейчас ничего по задачам не приходит,

**Comment by hirurg-lybitel** [comment]
> И распишите алгоритм, с какой периодичностью приходят уведомления пользователю.
> 
> 1. если пользователь закрыл уведомления, когда придут повторные?
> 2. если пользователь не закрывал, то повторно не должны приходить.

![image](https://user-images.githubusercontent.com/11502258/230696868-b91d1df1-eb3d-43e1-8995-df2a46378833.png)

1. Если пользователь нажал Удалить уведомление, то оно не удаляется сразу, а помечается, как Удаляемое.
Если через 60 минут (второй параметр на скрине) причина уведомления будет устранена, то это уведомление удалиться и больше не появится.
Если же причина так и не будет устарнена, то признак Удаляемое очиститься и уведомление снова появится.

2. Да, не должны
