### ISSUE TITLE
Проверка прав

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#121]
Добавить к существующей проверке

- [x] проверку прав маршрутов
- [x] проверку прав на бэке (passport/authenticate)

https://habr.com/ru/post/435106/

**Comment by hirurg-lybitel** [comment]
Добавил сотрудника ПЭО в группу Начальники отделов;
![image](https://user-images.githubusercontent.com/11502258/222863652-8f4a15b2-2a86-4af5-b3c1-2b4bd5d2baf0.png)

Вот такие права у группы:
![image](https://user-images.githubusercontent.com/11502258/222863805-3a707d13-7bfc-4290-adac-bfa35bc6a85b.png)

Разлогинился и зашёл по этому пути `http://localhost:4201/employee/preferences/permissions/list` и пустило, хотя прав на это нет.
![image](https://user-images.githubusercontent.com/11502258/222863983-cf51ba79-ebc7-416e-9b58-2284e48985c4.png)

Если что-то нажать, то выдаст ошибку:
![image](https://user-images.githubusercontent.com/11502258/222864082-739f47b3-2bca-4e75-be1a-16795395a96c.png)


В принципе хорошо, но мы не с англичанами работаем, поэтоум все сообщения должны быть на русском

**Comment by hirurg-lybitel** [comment]
Думаю, не стоит при проверке прав на роутах каждый раз образатсья к базе, это сильно тормозит все запросы. 
Подумать над реализацией кэшированной таблицы с правами, к которйо и обращаться.

Подумать над общим мидлваром на все роуты или групы роутов вместо мидлвара отдельно на каждый эндпоинт

**Comment by sashazernin** [comment]
на счет кэшированной таблицы, щас сидел думал как можно это лучше всего сделать, на ум пришло только такой варик: создать объект:
const permissions:any = {

}
и туда добавлять свойства где именем будет являться код права а значением 0 или 1 - т.е есть права или нет.

**Comment by hirurg-lybitel** [comment]
> на счет кэшированной таблицы, щас сидел думал как можно это лучше всего сделать, на ум пришло только такой варик: создать объект: const permissions:any = {
> 
> } и туда добавлять свойства где именем будет являться код права а значением 0 или 1 - т.е есть права или нет. Но надо будет при изменении прав менять и этот объект.
> 

Ну такое себе.
Уверен, есть множество библиотек для работы с кэшированной памятью для скорости. По сути да, туда записать простейший json и его дёргать. 

> на счет общего мидлвара: не знаю как можно сделать общий мидлвар там же в любом случае надо как то понимать для какого эндоинта какое право должно быть. Тоже самое и с emun в котором actioncode хранятся нужно какое то статичное поле но если оно будет зачем тогда обращаться к actioncode если есть это поле.

Самый простой вариант передавать в хедере запроса код операции и пользователя и в общем мидлваре проверять их

**Comment by sashazernin** [comment]
> 
> Самый простой вариант передавать в хедере запроса код операции и пользователя и в общем мидлваре проверять их

уверен что так лучше? мне кажется как это сейчас реализовано лучше там в любом случае коды из енама берутся

**Comment by sashazernin** [comment]
> Нет, не уверен. Надо пробовать несколько вариантов и сравнивать. Только так лучший и найдём для конкретной цели.

ты писал про избегания повторения кодf но если переделать так как ты говоришь то придется каждый раз добавлять хэдеры с кодом + шифровать сами коды. повторяемость остается а работы прибавляется. + всегда есть риск что злоумышленник сможет дешифровать данные.

**Comment by sashazernin** [comment]
могу предложить такой вариант: определять код по пути запроса

**Comment by sashazernin** [comment]
Все решения в этом пулреквесте Permissions #203

**Comment by hirurg-lybitel** [comment]
Тестируем то, что в мастере

**Comment by hirurg-lybitel** [comment]
по ошибке переоткрыл
