### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#130]
Разобраться с настройкой докера для проекта, чтобы можно было разворачивать на новых машинах без продолжительных танцев с бубном

**Comment by hirurg-lybitel** [comment]
@sashazernin 
Немного изменилось содержание `.env.sample`
Поэтому актуализировать свой `.env` и запустить `docker compose up -d`

**Comment by hirurg-lybitel** [comment]
@sashazernin проверь, пожалуйста,  пару моментов:
- работа проекта, запущенного через start:prod
- обновление страницы в клиенте, запушенным в образе

**Comment by sashazernin** [comment]
> @sashazernin проверь, пожалуйста, пару моментов:
> 
> * работа проекта, запущенного через `start:prod`
> * обновление страницы в клиенте, запущенным в образе

1.

**Comment by hirurg-lybitel** [comment]
Я, наверное, некорректно выразился.
Понятное дело, что если я написал про эти пункты, то знаю, что с ними что-то не так, и "проверь" тут значит получить те же проблемы и исправить их

**Comment by hirurg-lybitel** [comment]
@sashazernin поменялась немного структура .env. Смотри обновлённую инструкцию или коммит

**Comment by sashazernin** [comment]
С этим ишью все вопросы уже вроде порешали так что я закрою его
