### ISSUE TITLE
Завершённые сделки

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#141]
> Добавить признак "Завершена". 
> Устанавливать на любом этапе.
> Установка признака "Отказ" на любом этапе.

**Comment by hirurg-lybitel** [comment]
@hjamesgs А в какой этап должны попадать эти сделки?

**Comment by hjamesgs** [comment]
Отображаться на последнем этапе.
Но также добавить в фильтрацию сверху меню всех сделок.

**Comment by hirurg-lybitel** [comment]
> Отображаться на последнем этапе. Но также добавить в фильтрацию сверху меню всех сделок.

Так последний этап - это Отказы. И  оба типа этих сделок туда отправлять?

**Comment by hjamesgs** [comment]
Давай ещё добавим в Сделку признак "Обратная связь". Будут заполнять, если с клиентом пообщались.

Можно будет последнюю закладку обозвать как-то обобщенно: "Завершено" . В ней будут и Отмена и Обратная связь и Отказ. 
А фильтрацию сверху настроить на эти признаки

**Comment by hirurg-lybitel** [comment]
Добавлена галочка Отказ.
Последняя колонка переименована в Завершённые, в которую и попадают отказники.
