### ISSUE TITLE
Убрать милькания темы приложения

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#150]
Вместо прелодера сделать скелетон и убрать милькания

**Comment by sashazernin** [comment]
чтобы утрать милькания темы, нужно чтобы ответ от сервера, с темой, быстро приходил, тоже самое и с правами (нельзя скрывать недоступные пользователю кнопки, потому что, пока будет грузится кнопки будут показаны). Самое простое что можно сейчас сделать это записывать тему в куки, и когда будет заходить пользователь

**Comment by hirurg-lybitel** [comment]
Мелькаяния происходят, потому что у тебя нарушена логика. 

Сначала у тебя идёт авторизация, затем отрисовывается интерфейс, азатем только идёт запрос на получение настроек этого самого интерфейса. 

Как я и говорил изначально, настройи темы надо записывать в куки при авторизации, т.е. до отрисовки интерфейса

**Comment by hirurg-lybitel** [comment]
> чтобы утрать милькания темы, нужно чтобы ответ от сервера, с темой, быстро приходил, тоже самое и с правами (нельзя скрывать недоступные пользователю кнопки, потому что, пока будет грузится, кнопки будут показаны). Самое простое что можно сейчас сделать это записывать тему в куки, и когда будет заходить пользователь у которого стоит темная тема, когда до этого был пользователь с белой, тема будет менятся как в куки так и в сторе, но будет задержка.

Мелькаяния происходят, потому что у тебя нарушена логика.

Сначала у тебя идёт авторизация, затем отрисовывается интерфейс, азатем только идёт запрос на получение настроек этого самого интерфейса.

Как я и говорил изначально, настройи темы надо записывать в куки при авторизации, т.е. до отрисовки интерфейса

**Comment by sashazernin** [comment]
тогда почему нельзя тоже самое сделать и для прав?
