### ISSUE TITLE
Сохранение Сделки

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#156]
При добавлении сделки добавить кнопку "Сохранить". Без сохранения закладка "Задачи" не доступна.

**Comment by hirurg-lybitel** [comment]
так а решение какое?

**Comment by sashazernin** [comment]
Добавил кнопку "Добавить задачи" при нажатии создается сделка попап не закрывается и вкладка задачи становится доступной и открывается и можно задачи заполнить.

**Comment by hirurg-lybitel** [comment]
@hjamesgs нужна верификация от тебя по полученному решению

**Comment by hirurg-lybitel** [comment]
@sashazernin тебе написал @hjamesgs? 
Или почему ты задачу закрыл?

**Comment by sashazernin** [comment]
> @sashazernin тебе написал @hjamesgs? Или почему ты задачу закрыл?

не видел чтобы он писал что то

**Comment by sashazernin** [comment]
> @hjamesgs земля тебе пухом
