### ISSUE TITLE
Перепутаны страницы для источника заявок и причины отказа

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#169]
![image](https://user-images.githubusercontent.com/94962537/218545697-beca7904-0cb8-4f07-9a6f-9a381067f418.png)
![image](https://user-images.githubusercontent.com/94962537/218545795-d5d90488-bf01-4761-ac0a-e82862da84d0.png)

**Comment by hirurg-lybitel** [comment]
Не всё так плохо, просто перепутан текст
