### ISSUE TITLE
Группы пользователей. Поиск пользователя по ФИО

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#180]
![image](https://user-images.githubusercontent.com/11502258/222862563-14231eed-9ed5-4ede-b7ca-6c9f79e18d20.png)

Сейчас при вводе текста в поле выборапользователя поиск происходит только по логину (MatDepot).
Надо добавить возможность искать пользователя и по ФИО (Бухгалтерия)

**Comment by sashazernin** [comment]
На такте случаи было бы хорошо иметь бд нормального вида

**Comment by sashazernin** [comment]
Нашел баг добавлю его к этому заданию: можно отправить форму с не заполненным полем
![image](https://user-images.githubusercontent.com/94962537/225088473-eae6aa6c-ce42-415d-b9ab-b63322639289.png)

**Comment by hirurg-lybitel** [comment]
> На такие случаи было бы хорошо иметь бд нормального вида

Ты можешь в базе переименовать записи, как хочешь
