### ISSUE TITLE
Клиенты. Убрать поле папка и всех по умолчанию кидать в Организации

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#181]

**Comment by sashazernin** [comment]
feat: removed the folder field and added "Organizations" by default #200

**Comment by hirurg-lybitel** [comment]
Такие вещи не делаются на клиенте, иначе api работать не будет.
Это должно обрабатываться на бэке.

**Comment by hirurg-lybitel** [comment]
почему ты опят закрыл задачу, хоть я сказал, что она неправильно сделана?
