### ISSUE TITLE
Сделки. Автоматически обновлять список сделок

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#184]
Если окно уже открыто у одного пользователя, то никаие изменения друих пользователй не будут видны, пока не перезагрузигш страницу

**Comment by sashazernin** [comment]
я так понял можно это сделать через Websocket, https://redux-toolkit.js.org/rtk-query/usage/streaming-updates#websocket-chat-api-with-a-transformed-response-shape посмотрел сделать как это можно сделать в редаксе но что то у меня ничего не работает.

**Comment by sashazernin** [comment]
https://github.com/gsbelarus/gdmn-nxt/tree/autoupdate-kanban-cards попробовал сделать еще раз все так же не работает, глянь что я не так написал

**Comment by sashazernin** [comment]
> > https://github.com/gsbelarus/gdmn-nxt/tree/autoupdate-kanban-cards попробовал сделать еще раз все так же не работает, глянь что я не так написал p.s такой вывод данных временный, консоль логи и any тоже
> 
> У нас уже используется socket.io. Не стоит ещё один сокет подключать
> 
> Твой пример вроде тоже годный, проверю уже в понедельник

ну тут от rtk query способ но но что не не получается через него сделать
