### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#191]
- [x] 1.

Если сначала открыть Уведомления, а потом нажать на пользователя, то появляются скролы:
![image](https://user-images.githubusercontent.com/11502258/222868987-7cd2dee3-17a1-414c-a9c9-e84332e04092.png)

- [x] 2.

Если посворачивать меню, то убегают поля на графике:
![image](https://user-images.githubusercontent.com/11502258/222869133-9a0ca7d3-0754-4e8b-8366-439aa2354d31.png)

- [x] 3. 

Вроде ты уже это исправлял, может затёрлось что случайно.

В тёмном режиме не видно цифр:
![image](https://user-images.githubusercontent.com/11502258/222869189-e5fb1292-b1f0-496f-9b03-83b3226d54fa.png)

**Comment by sashazernin** [comment]
При сворачивании и разворачивании меню поля узжают
![image](https://user-images.githubusercontent.com/94962537/222996453-f2a2daa8-7622-4d13-a63e-ec305fb1739e.png)

**Comment by sashazernin** [comment]
Сделать подходящий скелетон
![image](https://user-images.githubusercontent.com/94962537/223221841-ed01b7bd-1aa4-4126-ab54-3c1c273a9080.png)
![image](https://user-images.githubusercontent.com/94962537/223221885-437697f6-402f-4067-881a-011d80e2d906.png)

**Comment by sashazernin** [comment]
Выровнять графики по правому краю
![image](https://user-images.githubusercontent.com/94962537/224112389-96314da0-a9b9-433a-9b30-27fd84367aab.png)

**Comment by sashazernin** [comment]
5. так как подвинуть конкретно график проблемотично(там нету никаких падингов и марджинов) убрал падинг страницы и подпинул все остальные элементы
