### ISSUE TITLE
База знаний. Заполнение

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#192]
Напиши, пожалуйста, сида какой-нибудь типовой вопрос по работе с срм, если знаешь, чтобы могли базу знаний немного заполнить ответами

**Comment by sashazernin** [comment]
а в чем проблема заполнить базу знаний через существующий запрос?

**Comment by sashazernin** [comment]
Как настроить личный кабинет?

**Comment by hjamesgs** [comment]
По данному вопросу пока ничего не делаем.
