### ISSUE TITLE
Доска сделок

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#201]
- [ ] 1. Думаю нужно либо отключить это перетягивание либо добавить возможность перемещения по доскам. Как мне кажется лучше второй вариант. я бы при перемещении выводил попап если, к примеру, перемещает в "к исполнению" появляется попап где надо выбрать исполнителя или будет открываться попап с редактированием.
![image](https://user-images.githubusercontent.com/94962537/227470262-b6d26194-6278-492c-93fb-928a007d013b.png)
- [ ] 2. Поле называется обратная связь, хотя перемищение туда происходит при отказе.
![image](https://user-images.githubusercontent.com/94962537/227471075-e897aad8-d498-428c-95d8-7e2c30f04865.png)
- [ ] 3. Еще бы сделал курсок poiter пр наведении на сделку, не понятно что она кликабельна.

**Comment by sashazernin** [comment]
@hirurg-lybitel отпиши как поступить?

**Comment by hirurg-lybitel** [comment]
1.  Перемещения между этапами происходят по строгой логике, которая ещё может меняться на этапе внедрения. 
Чтобы не переделывать всплывающие окна, лучше сначала внедрить, получить конечную логику, и потом уже по ней можно что-то менять.
Перетягивания внутри этапа нужны.
2.  А ты пи с префиксом CRM на базе своей обнови и будет тебе новое название колонки
3.  Сейчас курсор в виде руки, но глючит при первом наведении. Да, с этим стоит разобраться.
https://user-images.githubusercontent.com/11502258/227593664-c7d0e8b5-cb43-4fc0-afec-81fa8310f1e1.mp4

**Comment by hirurg-lybitel** [comment]
@sashazernin пунт 3 сделал?

**Comment by sashazernin** [comment]
> @sashazernin пунт 3 сделал?

fix: cursor pointer #212
