### ISSUE TITLE
Редактирование Сделки

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#202]
При редактировании данных в уже существующей сделке выскакивает ошибка

![image](https://user-images.githubusercontent.com/11534388/228807781-86aef5c7-6d0c-47f1-89e0-1cd7670e761f.png)

**Comment by sashazernin** [comment]
Напиши пути по воспроизводству, у меня все нормально работает

**Comment by sashazernin** [comment]
> Напиши путь по воспроизводству, у меня все нормально работает

@hjamesgs

**Comment by hjamesgs** [comment]
Не получилось воспроизвести. может какойто локальный глюк был.
