### ISSUE TITLE
Форма Клиенты. Ошибка при сортировке.

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#206]
Ошибка, когда нажимаешь сортировать по колонке Действия.
 
![image](https://user-images.githubusercontent.com/11534388/229980110-54bfdd63-ea47-4042-9641-00a188fafc09.png)

Может эту стрелочку можно вообще для этой колонки убрать?

**Comment by sashazernin** [comment]
fix: disable actions filter #213

**Comment by hirurg-lybitel** [comment]
это делается проще настройкой колонок
