### ISSUE TITLE
Форма Клиенты. Переделать дизайн.

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#207]
![image](https://user-images.githubusercontent.com/11534388/229980400-15e91717-4d92-426f-835c-0693d54c2ed1.png)

Сделать шапку меньше в 2 раза. 
Каждые блок сделать Уже (название Клиенты; Кнопка добавить со строкой поиска; Шапка таблицы)
а то для данных совсем мало места остается

**Comment by sashazernin** [comment]
Шапку с названием оставлю как есть т.к. как мне кажется будет лучше если она везде будет одного и того же размера

**Comment by hjamesgs** [comment]
Тогда везде сделай шапку меньше. Очень много места бесполезно используется. Чтобы до данных добраться, надо крутить вниз прокручивать.

**Comment by sashazernin** [comment]
шапку таблицы уменьшить не получилось т.к. сбивается высота блока с данными, точнее она остается такой же.

**Comment by hirurg-lybitel** [comment]
@hjamesgs 
На данный момент вот так сделали. Норм?
![image](https://user-images.githubusercontent.com/11502258/230735755-b956ca09-d5c1-4307-8ac8-471499b4e5eb.png)
