### ISSUE TITLE
Сделка. Форма редактирование

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#209]
При Редактировании Сделки, если ничего не меняли, сделать чтобы окно Сделка закрывалось через "Esc".
Сейчас или надо нажимать "Отмена", "Сохранить" или где-то на форме.

**Comment by sashazernin** [comment]
почему то при открывшемся попапе редактиования сделки при нажатии именно esc не срабатывает лисенер https://github.com/gsbelarus/gdmn-nxt/tree/deals
