### ISSUE TITLE
Окно уведомления. Изменить дизайн

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#210]
![image](https://user-images.githubusercontent.com/11534388/229987175-10f4c2ef-1a17-4de0-8b35-277fb2ffb9c1.png)

- [ ] 1. Шапку окна (Строчка "Уведомления") сделать Уже.
- [ ] 2. Слово Напоминание убрать. 
- [ ] 3. Если это уведомление к Сделке, то написать "Сделка" "Наименование сделки" "Клиент" "Срок сделки" (Дата время)
- [ ] 4. Если это уведомление к Задаче, то написать "Задача" "Описание задачи" "Срок задачи"  (Дата время)  ... к сделке "Сделка"
- [x] 5. Добавить дату и время, когда пришло уведомление. **(на твоём скрине она есть)**

**Comment by hirurg-lybitel** [comment]
ты уверен, что нужно так много информации в обычном уведомлении?

**Comment by hirurg-lybitel** [comment]
Перенесено в https://github.com/gsbelarus/gdmn-nxt/issues/248
