### ISSUE TITLE
Задачи. Окно редактирования.

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#211]
Поле "Описание" сделать на 3 строчки
![image](https://user-images.githubusercontent.com/11534388/229988909-c7abc056-df99-4427-b220-0e51f7a70d2a.png)

**Comment by hirurg-lybitel** [comment]
@sashazernin

**Comment by sashazernin** [comment]
chore: 3 rows for description #216

**Comment by hirurg-lybitel** [comment]
Не надо ничего делать, компонент и так растягивается по вертикали, если текста много.
А пустые строки нам иметь не надо, если всё влазит в одну строку
