### ISSUE TITLE
Клиеты

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#214]
- [x] 1

https://user-images.githubusercontent.com/94962537/230409547-31b21899-dfe7-4361-a588-6a03316a12c0.mp4

- [ ] 2

https://user-images.githubusercontent.com/94962537/230415090-f03dfbca-392c-4633-aeb9-c1b59ae0b064.mp4

**Comment by sashazernin** [comment]
https://user-images.githubusercontent.com/94962537/230415090-f03dfbca-392c-4633-aeb9-c1b59ae0b064.mp4

**Comment by sashazernin** [comment]
> * [ ]  2

`useEffect(() => {
    const newCustomers = customersData?.map((customer) => {
      const DEPARTMENTS: IContactWithID[] = [];
      customersCross?.departments[customer.ID]?.forEach((el: number) => {
        const department = departments?.find((wt) => wt.ID === el);
        if (!department) return;
        DEPARTMENTS.push(department);
      });

      const JOBWORKS: IWorkType[] = [];
      customersCross?.jobWorks[customer.ID]?.forEach((el: number) => {
        const wotkType = wotkTypes?.find((wt) => wt.ID === el);
        if (!wotkType) return;
        JOBWORKS.push(wotkType);
      });

      const CONTRACTS: ICustomerContract[] = [];
      customersCross?.contracts[customer.ID]?.forEach((el: number) => {
        const customerContract = customerContracts?.find((wt) => wt.ID === el);
        if (!customerContract) return;
        CONTRACTS.push(customerContract);
      });

      return {
        ...customer,
        DEPARTMENTS,
        CONTRACTS,
        JOBWORKS
      };
    });

    setCustomers(newCustomers);
  }, [
    customerFetching,
    customersData,
    customersCross,
    wotkTypes,
    departments,
    customerContracts,
    businessProcesses
  ]);`

Это из-за этого useEffecta, не понимаю для чего он вообще нужен?

**Comment by sashazernin** [comment]
![image](https://user-images.githubusercontent.com/94962537/232523663-5368c8db-940c-4ca0-8df4-9a5b9150d291.png)

что то совсем непонятное данные одни а отображается другое

**Comment by hirurg-lybitel** [comment]
вернул пока всё к старому варианту без optimistic update
