### ISSUE TITLE
Определение текущей страницы

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#220]
Поведение 1:

1. Зашёл на страницу метки
2. Сделал логаут
3. Сразу же залогинился снова
4. Меня перенаправило на главную страницу, но в меню выбран пункт Метки

Поведение 2:

1. Ещё не логинился
2. Перехожу по ссылке http://localhost:4201/employee/managment/labels
3. Меня перенаправило на главную страницу, но в меню выбран пункт Метки

Поведение 3:

1. Делаю обычный вход по адресу http://localhost:4201/
2. Открывается главная страница, но активного пункта меню вообще нет

Ожидаемое поведение:
Выбранный пункт меню должен соответствовать текущей странице

**Comment by sashazernin** [comment]
На самом деле вообще не понимаю для чего было привязывать активный пункт меню к переменной, можно было бы подсвечивать активную кнопку меню в зависимости от url. И не нужно было бы мне делать этот, по сути, костыль для нормального отображения меню. Вообще могу переделать чтобы без костылей было.

```
const Link = (props) => {
    const isActive = ({isActive}) => (isActive ? c.activeLink : c.link)
    return (
        <NavLink className={isActive} to={props.path}>{props.name}</NavLink>
    )
}

const LicksCount = () => {
    return (
        <>
            <Link path={'RandomCat'} name={'Random Cat'}/>
            <Link path={'Vote'} name={'Vote'}/>
            <Link path={'Votes'} name={'Votes'}/>
            <Link path={'Favorites'} name={'Favorites'}/>
            <Link path={'FindImage'} name={'Find image'}/>
            <Link path={'Upload'} name={'Upload'}/>
            <Link path={'About'} name={'About'}/>
        </>
    )
}
```

**Comment by sashazernin** [comment]
https://github.com/gsbelarus/gdmn-nxt/pull/224

**Comment by hirurg-lybitel** [comment]
> На самом деле вообще не понимаю для чего было привязывать активный пункт меню к переменной, можно было бы подсвечивать активную кнопку меню в зависимости от url. И не нужно было бы мне делать этот, по сути, костыль для нормального отображения меню. Вообще могу переделать чтобы без костылей было.
> 
> Пример:
> 
> ```
> const Link = (props) => {
>     const isActive = ({isActive}) => (isActive ? c.activeLink : c.link)
>     return (
>         <NavLink className={isActive} to={props.path}>{props.name}</NavLink>
>     )
> }
> 
> const LicksCount = () => {
>     return (
>         <>
>             <Link path={'RandomCat'} name={'Random Cat'}/>
>             <Link path={'Vote'} name={'Vote'}/>
>             <Link path={'Votes'} name={'Votes'}/>
>             <Link path={'Favorites'} name={'Favorites'}/>
>             <Link path={'FindImage'} name={'Find image'}/>
>             <Link path={'Upload'} name={'Upload'}/>
>             <Link path={'About'} name={'About'}/>
>         </>
>     )
> }
> ```
> 
> Можешь еще глянуть код моего проекта, как там реализовано: https://github.com/sashazernin/React-project-cats

Так ради бога. Если ничего не сломается, то улучшения только приветсвуются

**Comment by sashazernin** [comment]
в общем переделал теперь этот костыль не нужен.
