### ISSUE TITLE
Окно поиска клиента по названию

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#221]
![image](https://user-images.githubusercontent.com/11502258/230736983-1ee20f94-1c99-4139-84df-4557b4983daf.png)

Поведение:

1. Включаем тёмную тему
2. Нажимаем на компонент - граница меняет цвет на какой-то серый
3. Нажимаем на компонент - граница меняет цвет на какой-то серый

Ожидаемое поведение:
Таке же, как у других фильтров при наведении и нажатии

**Comment by sashazernin** [comment]
chore: border color for field find client #225
