### ISSUE TITLE
Один и тот же пользователь в одной группе

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#227]
![image](https://user-images.githubusercontent.com/94962537/233130143-b05bef0a-2f59-4a95-aac7-34d8075eff74.png)

Можно добавить сколько угодно раз пользователя в группы, сделать ограничение для добавление только одной записи, а если пользователь находится в другой группе удалять его из нее.

**Comment by hirurg-lybitel** [comment]
Удалять что-то из программы без ведома пользователя?
А если он просто не знал, что пользователь уже добавлен в другую группу, или просто ошибся?

Это абсолютно неверный подход. Как минимум человек должен понимать, что есть какая-то коллизия, а лучше ещё и программа должна предлагать её решение.

**Comment by hirurg-lybitel** [comment]
Переделал немного по-другому
*забыл привязать к ишью
https://github.com/gsbelarus/gdmn-nxt/commit/e5471cb5e43b460746777293942949ee56f0aec0
