### ISSUE TITLE
Сделки. Добавить дату исполнения и срок просрочки

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#239]
![image](https://user-images.githubusercontent.com/11502258/236294210-92b861eb-5ca0-4bc0-8909-d9c039988738.png)

**Comment by sashazernin** [comment]
https://github.com/gsbelarus/gdmn-nxt/commit/ba7afb7116e6d7f841689374d7d6b249149accc1
