### ISSUE TITLE
Уведомления. 

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#248]
Состоит из 4х блоков
1. Тематика Уведомления (жирным)
Виды тематики уведомлений: **«Новая задача или Сделка»**, **«Просроченная задача или Сделка»**, **«Пора выполнить задачу или сделку»**
**«Новая задача/ Сделка»** -  признак "В работе" пустой
**«Просроченная задача или Сделка»** - как и сейчас. дата/время исполнения больше Срока исполнения.
**«Пора выполнить задачу или сделку»** - приходит Исполнителю за 1 час (по умолчанию) до истечения срока Задачи (если указано время), если времени нет – то за сутки (по умолчанию), время уведомления – время отправки уведомления (то есть за 1 час, за сутки до дня срока). 

2. Наименование. Для Задачи  - это Тип задачи + Описание, для Сделки - поле Наименование

3.  Исполнитель/Постановщик
    Если пользователь Исполнитель - сообщение "Постановщик 'имя Пользователя'"
    Если пользователь Постановщик - сообщение "Исполнитель 'имя Пользователя'"

4. Дата время 
   Если это Новая задача/сделка  - выводить дату и время Создания
   Для других этапов - выводить дату и время Срока исполнения.

**Comment by hjamesgs** [comment]
Размер окна оставить примерно такой же. Если  текст  Описания задачи/сделки не будет влазить, выводить в 2 строки. остальной текст обрезать.

**Comment by hirurg-lybitel** [comment]
Пункт 3 на данный момент невозможен. Будет просто исполнитель указан всегда
