### ISSUE TITLE
Система оповещения об обновлении

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#250]
- [x] при обновлении ПО каждый пользователь при первом заходе получает окно с информацией об новых изменениях
- [x] хранение истории обновления, чтобы можно было посмотреть в какой версии что появилось

**Comment by sashazernin** [comment]
а сам текст об обновлениях откуда брать или просто добавить возможность а текст уже будет писатся кем либо?

**Comment by hirurg-lybitel** [comment]
Кто-то куда-то должен будет внести его предварительно
