### ISSUE TITLE
Переход на сделку из Оповещения

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#253]
Пользователю поставлена в Сделке Задача, Уведомление пришло. При переходе на сделку  ничего не отображается.
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/444e5b63-e76d-4cea-9ecb-f4855c6ec777)

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/f202d7ae-276c-4ecb-9ff8-7e177be08604)

**Comment by hirurg-lybitel** [comment]
@hjamesgs Так а что за пользователь? Какие данные у сделки?

**Comment by hjamesgs** [comment]
пользователь - это исполнитель в **Задаче**
Задача в Сделке.

**Comment by hirurg-lybitel** [comment]
> пользователь - это исполнитель в **Задаче** Задача в Сделке.

Так откуда я знаю, какой там исполнитель? 
Мне же нужный хоть какие-то данные дял воспроизведения ситуации

**Comment by hirurg-lybitel** [comment]
Прояснения так и нет, поэтому закрываю за неактуальностью
