### ISSUE TITLE
Клиенты. Оптимистичное обновление

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#264]
Сейчас crud операции в данном справочнике выполняются синхронно в реальном времени.
На примере обновления это выглядит так: 

- пользователь нажал Сохранить 
- пошёл запрос put на бэк 
- пришёл ответ от бэка 
- пошёл запрос get на бэк
- данные у пользователя обновились

Для ускорения этого процесса для пользователя надо использовать [optimistic update](https://redux-toolkit.js.org/rtk-query/usage/manual-cache-updates#:~:text=Optimistic%20Updates%E2%80%8B,request%20is%20still%20in%20flight.).
Должно получится так:
- пользователь нажал Сохранить 
- новые данные сразу изменили текущий кэш
- данные у пользователя обновились
- пошёл запрос put на бэк 
- если всё ок, то на этом всё
- если была ошибка, то кэш откатился к предыдущему состоянию и у пользователя снова обновилась картинка

**Comment by sashazernin** [comment]
я так понимаю это надо сделать для каждого запроса
