### ISSUE TITLE
Клиенты. Форма просмотра.

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#271]
Добавить новую закладку   Сделки
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/cca653e2-7d70-4898-8024-0176faa7327e)

Списком выводить информацию:

**Сделка** "Наименование"  "ТекущийСтатус" "ДатаСоздания"   **Заявка** "Номер" "Наименование" "Дата"

**Comment by hirurg-lybitel** [comment]
Если вспомнишь, то Дата создания и Дата заявки - это у нас одно и то же, 

В общем пока так сделал
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/77fcf856-8f95-48cb-b0cf-75a08f435554)
