### ISSUE TITLE
Создание сделки. 

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#282]
Создаем новую сделку.
Нажимаем кнопку "Добавить задачи". Кнопка становиться не активной. "Сохранить" не активна. На закладку "Задачи" не переходит. Хотя сама сделка сохраняется.

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/d9d35d60-c069-4fc7-9c2f-078ac3175199)

**Comment by hirurg-lybitel** [comment]
И так всё остаётся висеть или спустя некоторые время проходит?
