### ISSUE TITLE
Скролл

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#285]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/aa1f5e6c-dde4-4023-8dc0-dcc5bf481d51)

**Comment by hirurg-lybitel** [comment]
Нет, не должно. Исправлю

**Comment by hirurg-lybitel** [comment]
@sashazernin 
Обнови, проверь и закрой, если всё ок, пожалуйста

**Comment by hirurg-lybitel** [comment]
@sashazernin
Обнови, проверь и закрой, если всё ок, пожалуйста
