### ISSUE TITLE
#28 Уведомления. Переход на Задачу

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#301]
Задача №28
по поиску не находится
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/8d8b5f9d-f194-40b2-a963-b577b857acdb)

ни под постановщиком ни под исполнителем не отображается

**Comment by hirurg-lybitel** [comment]
А такая задача видна под админом?
Возможна ситуация, когда создали задачу, уведомление об этом пришло, а потом задачу удалили просто

**Comment by hirurg-lybitel** [comment]
Пояснений нет. Закрываю
