### ISSUE TITLE
Задачи. Оптимистичное обновление

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#311]
Обновлять задачи после crud операций, а также манипуляций со сделками

**Comment by sashazernin** [comment]
@hirurg-lybitel могу попробовать эту задачу

**Comment by hirurg-lybitel** [comment]
Пробуй.

Делать через сокет

**Comment by hirurg-lybitel** [comment]
Необходимо добавить ограничение обновления по пользователям, иначе все будут видеть обновление всех
