### ISSUE TITLE
Подключить ssl

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#316]
- [x] Нужно перейти на https, чтобы можно было подключаться к демо версии по доменному имени вместо ip:port
- [ ] сделать то же самое для докера
- [ ] используя офисные сертификаты, перейти на доменное имя

**Comment by hirurg-lybitel** [comment]
@sashazernin 
На ветке feature-ssl уже подключил ssl для самого приложения, но надо разобраться, как подключить и сокеты на фронте к ssl

**Comment by hirurg-lybitel** [comment]
@sashazernin какие успехи?

**Comment by sashazernin** [comment]
> @sashazernin какие успехи?

пока что этим не занимаюсь

**Comment by sashazernin** [comment]
решил проблемы с протоколом сменой порта, но появилась другая ошибка ERR_CONNECTION_REFUSED гуглил но ничего дельного не нашел.
