### ISSUE TITLE
Задачи. Список

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#327]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/6a5fafbd-843c-4b67-ad13-3503eb5b1fe1)

1. Добавить колонку  - Постановщик
2. Сортировать задачи по дате и времени. Сверху списка самые новые даты
3. Вместо полного ФИО в колонках Исполнитель/Постановщик использовать поле NICKNAME из GD_PEOPLE

запрос типа того чтото
select
  COALESCE(p.NICKNAME, con.name) as username
from
  gd_user u
  left join GD_PEOPLE p on p.CONTACTKEY = u.CONTACTKEY
  left join GD_contact con on con.ID = u.CONTACTKEY
where
  u.ID = :userkey

**Comment by hirurg-lybitel** [comment]
2. сортировать по дате создания задачи `card.TASK.USR$CREATIONDATE `
3. Никнейм делать динамически, а не ждать из базы, по маске `Фамилия И. О.`
