### ISSUE TITLE
Отправка уведомлений на Email.

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#329]
Упрощенно реализовать возможность отправки уведомлений на Е-mail.
Е-mail прописать для каждого пользователя.
У пользователя должен быть признак, отправлять ли на Е-mail.
Реализовать техническую возможность. Можно 1 раз в сутки отправлять пользователю все его "зависшие" уведомления.

**Comment by hirurg-lybitel** [comment]
1. В настройках аккаунта указать email и включить получение уведомлений по почте
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/e24bfb77-389c-4b9e-a828-a616a935a769)

2. Каждый час с 9-00 по 17-00 с пн. по пт. будут приходить такие сообщения 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/b97ea779-d7dc-4ebf-bced-ecf62a223d97)
