### ISSUE TITLE
Изменение статуса/этапа Сделки(Задачи)

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#332]
При изменении статуса/этапа Сделки(Задачи) необходимо "подсвечивать" Сделку(задачу) выделением. 
1. Для каждого пользователя своё выделение (Исполнитель1, Исполнитель2, Постановщик)
2. Сделка (Задача) должна быть первой в списке.

**Comment by hirurg-lybitel** [comment]
Обновить ПИ [GS.CRM.Метаданные.Таблицы.Kanban.Статусы карт](https://github.com/GoldenSoftwareLtd/gedemin-apps/commit/dc9ae597acf7a6bdc37ddcf68430f5ae65b8f4a0)
