### ISSUE TITLE
Сделка. Доп информация по первичным документам из учетной системы

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#340]
При редактировании Сделки добавить информацию в виде (пример)

Калькуляция № 10779 от 2023-04-18  на сумму 3522.97 руб.коп.  
Акт выполненных работ № 7556/2023 от 2023-05-03  на сумму 2301.31 руб.коп.  
Счет-акт № 32276/834 от 2023-03-22  на сумму 637.81 руб.коп.  
Договор № 460/23 от 2023-04-03  на сумму 1100.86 руб.коп.

Дополнительно:
Добавить поле в gd_document  doc.USR$DEALSKEY типа DINTEGER

Запрос
select
 doc.number, doc.DOCUMENTDATE,
  (select 'Калькуляция № '  docc.NUMBER  ' от '   CAST(docc.DOCUMENTDATE as date)  '  на сумму ' 
   CAST((select SUM(line.USR$VALUE) from USR$PD_CALCLINE line where line.MASTERKEY = c.DOCUMENTKEY
     and line.USR$ACTIVITIESKEY = 189467574) as NUMERIC(15,2))  ' руб.коп.'
   from USR$PD_CALC c join  gd_document docc on docc.id = c.DOCUMENTKEY
   where docc.USR$DEALSKEY = r.USR$CRM_DEALKEY) as Calc,
  (select 'Акт выполненных работ № '  docact.NUMBER  ' от '   CAST(docact.DOCUMENTDATE as date)  '  на сумму ' 
   CAST(  act.USR$SUMWITHNDSNCU  as NUMERIC(15,2))  ' руб.коп.'
   from USR$BG_ACT_CONTRAC act join  gd_document docact on docact.id = act.DOCUMENTKEY and docact.documenttypekey = 148476088
   where docact.USR$DEALSKEY = r.USR$CRM_DEALKEY) as Act,
  (select 'Счет-акт № '  docact2.NUMBER  ' от '   CAST(docact2.DOCUMENTDATE as date)  '  на сумму ' 
   CAST(  act2.USR$SUMWITHNDSNCU  as NUMERIC(15,2))  ' руб.коп.'
   from USR$BG_ACT_CONTRAC act2 join  gd_document docact2 on docact2.id = act2.DOCUMENTKEY and docact2.documenttypekey = 155594630 
   where docact2.USR$DEALSKEY = r.USR$CRM_DEALKEY) as Act2,

  (select 'Договор № '  docdog.NUMBER  ' от '   CAST(docdog.DOCUMENTDATE as date)  '  на сумму ' 
   CAST(  dog.USR$SUMM  as NUMERIC(15,2))  ' руб.коп.'
   from USR$BG_CONTRACT dog join  gd_document docdog on docdog.id = dog.DOCUMENTKEY
   where docdog.USR$DEALSKEY = r.USR$CRM_DEALKEY) as Dogovor

from
  gd_document doc
  join USR$BG_REQUESTOW r on r.DOCUMENTKEY = doc.id

where
  doc.DOCUMENTTYPEKEY = 349866728 /* Заявка ИЦ-26*/
  and r.USR$CRM_DEALKEY = :DEALKEY

**Comment by hirurg-lybitel** [comment]
> 
данный этот запрос не работает

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/7899360c-18ca-4a40-9cc5-3893e4b10344)

**Comment by hirurg-lybitel** [comment]
@hjamesgs 
Сделал так 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/fb4e7232-44b5-4bda-835a-e4dcd961772b)
