### ISSUE TITLE
Переход в Сделку из Задачи

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#348]
Переход в Сделку из Задачи.
Только для Постановщика сделки + Исполнителя 1  + Исполнителя 2

**Comment by hirurg-lybitel** [comment]
@hjamesgs
Тут непонятно по исполнителям.

В задаче только один исполнитель.
Исполнители же в сделках не видят задачи не для них.

Должен ли исполнитель задачи, который не является исполнителем сделки, иметь возможность такого перехода?

**Comment by hjamesgs** [comment]
Если Исполнитель в Задаче совпадает с Исполнителем 1 или Исполнителем 2 в Сделке, то переход разрешаем.
Иначе, нельзя.
пока так.
