### ISSUE TITLE
Шаблон для Задачи

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#350]
1. Добавить Глагол в тексте.
  
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/1089bb21-78e2-4fbd-a9d1-d9d25e695a6a)

2. Попробовать сделать разные шрифты и цвета
  типа 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/7840675d-8313-4258-9be4-e7aad99eeb23)
 а. если просрочено. красным цветом дата -время
 б. межстрочный интервал уменьшить. очень мало информации влазит.
 в. формат для даты записать 24.07.2023 18:00 
 г. в одну строку дата/время и Постановщик + Исполнитель. 
можно чуть шире сделать окно задачи.

**Comment by sashazernin** [comment]
> 1. Добавить Глагол в тексте.
> 
> ![image](https://user-images.githubusercontent.com/11534388/255667392-1089bb21-78e2-4fbd-a9d1-d9d25e695a6a.png)
> 
> 2. Попробовать сделать разные шрифты и цвета
>    типа
>    ![image](https://user-images.githubusercontent.com/11534388/255666497-7840675d-8313-4258-9be4-e7aad99eeb23.png)
>    а. если просрочено. красным цветом дата -время
>    б. межстрочный интервал уменьшить. очень мало информации влазит.
>    в. формат для даты записать 24.07.2023 18:00
>    г. в одну строку дата/время и Постановщик + Исполнитель.
>    можно чуть шире сделать окно задачи.

![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/37944ad3-23d0-4b05-b369-ee2d0c093278)
так не влезет же в одну строку и дедлайн и постановщик с исполнителем

**Comment by hirurg-lybitel** [comment]
@hjamesgs гуж?

**Comment by hjamesgs** [comment]
1. Не добавили Глагол
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/6612a2bd-6590-40ff-b6a0-3e953f0546e5)

2. Поменять шрифт (может жирным сделать, или другой размер, или шрифт, или цвет другой оттенок), где дата-время. На темной теме вообще сливается

**Comment by sashazernin** [comment]
> 1. Не добавили Глагол
>    ![image](https://user-images.githubusercontent.com/11534388/258022073-6612a2bd-6590-40ff-b6a0-3e953f0546e5.png)
> 2. Поменять шрифт (может жирным сделать, или другой размер, или шрифт, или цвет другой оттенок), где дата-время. На темной теме вообще сливается

мне не совсем ясно о каком глаголе идет речь

**Comment by sashazernin** [comment]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/930ae99a-1822-42b7-a43a-01c9881d9a13)

![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/9ba0c248-b876-4cf7-b315-9ac7b5707616)
