### ISSUE TITLE
Добавить страницу в Сделки

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#353]
- [ ] Добавить страницу в форму Сделки, в которой можно будет собираться информацию о общении с клиентов в данной сделке.

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/8f76e50d-fce6-45a8-8bbb-57db5815b6a8)

- [ ] Добавить справочник "Тип сообщения" (например, Письмо, Звонок, Переписка  и тп)

- [ ] В этой же форме отображать задачи с комментарием (если выполнена)

формат ввода сообщения:
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/d5ef4eaf-e370-41ff-820b-c8b35db598b4)

Выбираем "Тип сообщения" - Кто внес (по умолчанию Пользователь) - Кому (можно не заполнять)
Сохраняется дата и время сообщения.

Список (сообщения + Задач) сортировать по дате времени.

**Comment by sashazernin** [comment]
> * [ ]  Добавить страницу в форму Сделки, в которой можно будет собираться информацию о общении с клиентов в данной сделке.
> 
> ![image](https://user-images.githubusercontent.com/11534388/255675567-8f76e50d-fce6-45a8-8bbb-57db5815b6a8.png)
> 
> * [ ]  Добавить справочник "Тип сообщения" (например, Письмо, Звонок, Переписка  и тп)
> * [ ]  В этой же форме отображать задачи с комментарием (если выполнена)
> 
> формат ввода сообщения: ![image](https://user-images.githubusercontent.com/11534388/255676127-d5ef4eaf-e370-41ff-820b-c8b35db598b4.png)
> 
> Выбираем "Тип сообщения" - Кто внес (по умолчанию Пользователь) - Кому (можно не заполнять) Сохраняется дата и время сообщения.
> 
> Список (сообщения + Задач) сортировать по дате времени.

Для каждой сделки свой чат с котором задачи будут обсуждаться?

**Comment by hirurg-lybitel** [comment]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/ed494269-e045-438b-96a6-7ad9fa439bfe)
