### ISSUE TITLE
Новые этапы Сделок

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#354]
Этап 1. Новая  - как есть
Этап 2. Консультация - (нынешний этап 2  - к исполнению) просто переименовать
Этап 3. Принимают решение
Этап 4. Договор/Счет
Этап 5. Выполнения работ - (нынешний этап 3  - в работе) просто переименовать
Этап 6. Акт/накладная
Этап 7. Проверка оплаты (Добавить признак в сделку. Галочку. Можно заполнять начиная с 4-го этапа. Вывести значок в список сделок, например $ зеленым цветом, если оплата стоит, красный - если нет)
Этап 8. Завершение сделки (менеджер проверяет оплату, комплект документов и ставит признак Исполнено)
Этап 9. Исполнено.

описание по этапам будет дополнено

**Comment by hjamesgs** [comment]
Значок оплата в правом верхнем углу можно сделать, рядом с номером.
типа того, только знак  "$"
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/a664f5e2-2f11-434c-888b-7d395dacbe4c)

**Comment by hirurg-lybitel** [comment]
> Значок оплата в правом верхнем углу можно сделать, рядом с номером. типа того, только знак "$" ![image](https://user-images.githubusercontent.com/11534388/256238896-a664f5e2-2f11-434c-888b-7d395dacbe4c.png)

зачем, если только в одном этапе (Оплата) он будет зелёным?

**Comment by hjamesgs** [comment]
Про оплату. Начиная с 4-го этапа может быть и Предоплата, тк какие то работы не начинают без денег. Поэтому этот значок может отображаться в принципе на всех этапах.

**Comment by hjamesgs** [comment]
для перехода по Этапам сделать универсальную кнопку (стрелку) "Переход на следующий этап"
на всех этапах доступна
так же добавить кнопку - Вернуться на предыдущий этапа.

На сегодня это универсальное решение. в процессе работы будем автоматизировать переход между этапами.

**Comment by hirurg-lybitel** [comment]
Для узких мониторов переключение этапов стерлочками
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/cc9b1856-b0a7-461e-a4aa-8e77f2d0f15f)

Для царских мониторов переключение через нажатие на любой этап сверху
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/86fd3244-6467-47b7-a529-636be92b5e55)
