### ISSUE TITLE
Нет возможности открыть меню

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#362]
При уменьшении окна появляется мозможность закрыть левое меню а открыть его уже никак нельзя
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/24c5c538-544a-4bec-80d8-887ba4eb5162)

1. Уменьшить окно браузера до <900px 
2. нажать в любое место сайта

**Comment by hirurg-lybitel** [comment]
@sashazernin 
Переделать, чтобы в браузерной версии не закрывалось, а в мобильной меню было так же всплывающим, а бургер, аватар и прочее, как раньше, горизотальной полосой сверху
