### ISSUE TITLE
Баг при перемещении карточки 

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#377]
https://github.com/gsbelarus/gdmn-nxt/assets/11502258/d97ac9e1-63c0-4dca-9004-0871794594ba

**Comment by sashazernin** [comment]
не получилось баг воспроизвести

**Comment by sashazernin** [comment]
проблема на продакшене, сервер бд не успает поменять данные.

**Comment by sashazernin** [comment]
а на счет ддерганий могу предложить такой вариант: мануально бел оптимистического обновление изменять на фронте данные на кэшированные и когда приходит ответ от сервера менять на реальные.

**Comment by sashazernin** [comment]
> проблема на продакшене, бд не успевает поменять данные. На запущенном проекте через вс код или если поставить медленный интернет такой проблемы нет

как вариант можно сделать проверку изменились ли данные если не отправить еще раз запрос если опять не изменились не отправлять повторный (тк тогда уже данные точно те что надо).
