### ISSUE TITLE
Сделка. Признак "Отказ". Не фиксируется когда и на каком этапе

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#381]
Сделка. Признак "Отказ". Надо в Хронологию добавить, когда и на каком этапе!
Так же проверить для всех признаков. Дата-время - Кто поставил - Текущий этап сделки.

**Comment by hirurg-lybitel** [comment]
Так в хронологии вся эта информация есть же.

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/9d5bc10f-b5fc-4ff8-a6b0-06819c706d65)

Единственное, что не все признаки в хронологию заносятся
