### ISSUE TITLE
Клиенты. Просмотр

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#384]
После просмотра клиента через "глазик",  чтобы перейти в список (или поиск) клиента, нажимаешь "Клиенты" - заново перечитывается список клиентов.
Может добавить рядом какую кнопку, "Назад", чтобы опять в поиск зайти?

**Comment by hirurg-lybitel** [comment]
@sashazernin посмотри, есть ли какие-то "перечитывания" при указанных действиях

**Comment by sashazernin** [comment]
> Посмотрел запроса нового не идет когда обратно возвращаешься, данные те что были. Когда обратно к клиентам возвращаешься отправляется запрос http://localhost:3333/api/v1/worktypes можно

**Comment by hirurg-lybitel** [comment]
@hjamesgs не получается воспроизвести проблему. Всё работает так, как ты описал и должно работать.
У тебя такая проблема есть в демо-версии, что что-то сбрасывается или перечитвается?

**Comment by hjamesgs** [comment]
1. Нажимаем "Клиенты"

**Comment by hirurg-lybitel** [comment]
@sashazernin а с этим что? Нет комментариев никаких

**Comment by sashazernin** [comment]
не получилось воспроизвести

> @sashazernin а с этим что? Нет комментариев никаких

**Comment by hirurg-lybitel** [comment]
http://213.184.249.125:60105

**Comment by hirurg-lybitel** [comment]
@hjamesgs проблема актуальна на текущей версии?
