### ISSUE TITLE
В режиме редактирования профиля не отображается имя пользователя

### ISSUE THREAD

**Issue by AliakseiDanilchyk** [gsbelarus/gdmn-nxt#408]
В режиме редактирования профиля не отображается имя пользователя

**Comment by sashazernin** [comment]
У пользователя есть имя и логин (имя по которому пользователь входит в учетную запись), и возможно стоит еще добавить описание профиля, и изменение пароля.

**Comment by AliakseiDanilchyk** [comment]
Имя, как минимум, нужно. Типа "Добро пожаловать, John Smith"

**Comment by hirurg-lybitel** [comment]
> У пользователя есть имя и логин (имя по которому пользователь входит в учетную запись), добавлять оба? Возможно стоит еще добавить описание профиля, и изменение пароля. Эти данные есть в gd_user но не изменяются в профиле сейчас.

ФИО

Изменение пароля не нужно добавлять. И его не должно быть ни в каких данных.

Что такое "описание профиля"?

**Comment by sashazernin** [comment]
> > У пользователя есть имя и логин (имя по которому пользователь входит в учетную запись), добавлять оба? Возможно стоит еще добавить описание профиля, и изменение пароля. Эти данные есть в gd_user но не изменяются в профиле сейчас.
> 
> ФИО
> 
> Изменение пароля не нужно добавлять. И его не должно быть ни в каких данных.
> 
> Что такое "описание профиля"?

У пользователя администратор описание: "Администратор системы",

**Comment by sashazernin** [comment]
> ФИО
 
Сейчас на сайте используется поле name - оно же логин, давать возможность меня его или fullname?

**Comment by hirurg-lybitel** [comment]
Нет, пока не надо менять ничего.
