### ISSUE TITLE
Клиенты

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#41]
_Меню - Клиенты - Список клиентов_

![photo_2022-02-15_01-03-57](https://user-images.githubusercontent.com/11502258/153954203-0d52f66e-e974-4782-b683-91cb3d2cb1b9.jpg)

- [x] оптимизация запроса клиентов
- [x] фильтрация по заказам, отделам, меткам
- [x] #84
- [x] переход с кнопки Акт сверки на страницу Акт сверки с id выбранного клиента 
- [x] список договоров
- [x] возврат к списку клиентов без перезагрузки данных

**Comment by hirurg-lybitel** [comment]
@AntanovichV вот 4 пунктом заняться можно

**Comment by hjamesgs** [comment]
в п.6 рисунка вместо оборотов добавить  список договоров

select
  doc.DOCUMENTDATE,
  doc.NUMBER,
  c.USR$ACTIVE, /* Действующий*/
  c.USR$BUDGET, /* Бюджетный*/
  dep.name as depname, /* Отдел*/
  job.USR$NUMBER as jobnumber,/ * Заказ*/
  c.USR$SUMM, /*Сумма в руб*/
  c.USR$CURR, /*Сумма в вал*/
  c.USR$DATEBEGIN, /* дата начала */
  c.USR$DATEEND /* дата окончания*/
from
  USR$BG_CONTRACT c
  join gd_document doc on c.DOCUMENTKEY = doc.id
  join gd_contact dep on dep.ID = c.USR$CONTACTKEY
  join usr$bg_contractjob job on job.ID = c.USR$CONTRACTJOBKEY
where
  doc.DOCUMENTTYPEKEY = 148085034
  and
  c.USR$CUSTOMER = :id
order by
  doc.DOCUMENTDATE desc

**Comment by hirurg-lybitel** [comment]
![image](https://user-images.githubusercontent.com/11502258/174826528-9f926105-fd1c-420f-89d3-25777752e039.png)

**Comment by hjamesgs** [comment]
Не фильтрует при выборе «Вида работ»
![image](https://user-images.githubusercontent.com/11534388/184925720-bb291337-58b0-4cc8-ae3a-be9acf001daf.png)

**Comment by hjamesgs** [comment]
Не работает «глазик» и не отображается на маленьких мониторах

![image](https://user-images.githubusercontent.com/11534388/184925863-593b0b74-b821-42c6-b6fb-6fe3bf1ca276.png)
