### ISSUE TITLE
Бесконечная прокрутка в бок

### ISSUE THREAD

**Issue by sashazernin** [gsbelarus/gdmn-nxt#411]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/9ab22644-ab09-403e-9021-69b837fc0efe)

**Comment by hirurg-lybitel** [comment]
Не могу воспроизвести
Необходима какая-то определённая последовательность действий?

**Comment by sashazernin** [comment]
> Не могу воспроизвести Необходима какая-то определённая последовательность действий?


https://github.com/gsbelarus/gdmn-nxt/assets/94962537/bfb85eeb-155b-4f85-8722-01fb35d9aee0

**Comment by sashazernin** [comment]
надо уменьши экран

**Comment by hirurg-lybitel** [comment]
думаю, это ограничения компонента. Но можешь исправить

**Comment by hirurg-lybitel** [comment]
@sashazernin так какое решение?

**Comment by sashazernin** [comment]
> @sashazernin так какое решение?

да, думаю ты прав на счет того что это исключительная ситуация
