### ISSUE TITLE
Push-уведомления

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#416]
Добавить возможность отправлять наши уведомления в колокольчике через push-уведомления

**Comment by sashazernin** [comment]
надо добавить всплывающее уведомление как при ошибке?

**Comment by sashazernin** [comment]
https://mui.com/material-ui/react-snackbar/#complementary-projects

**Comment by hirurg-lybitel** [comment]
Не понял, а что сделано по задаче, если она закрыта?

**Comment by hirurg-lybitel** [comment]
> https://mui.com/material-ui/react-snackbar/#complementary-projects

это к чему?
Да, мы используем этот компонент для показа уведомелний внутри системы.

Задача подключить push-уведомелния. Это которые через браузер работают вне сайта

**Comment by sashazernin** [comment]
> > https://mui.com/material-ui/react-snackbar/#complementary-projects
> 
> это к чему? Да, мы используем этот компонент для показа уведомелний внутри системы.
> 
> Задача подключить push-уведомелния. Это которые через браузер работают вне сайта

не правильно понял задачу

**Comment by sashazernin** [comment]
https://www.npmjs.com/package/react-push-notification

Синтаксис:
import addNotification from 'react-push-notification';

**Comment by hirurg-lybitel** [comment]
Я не понимаю, зачем этот код тут пишешь?
В программе это надо реализовать

**Comment by sashazernin** [comment]
> Я не понимаю, зачем этот код тут пишешь? В программе это надо реализовать

ты же написал добавить возможность, а не отправлять push уведомления а добавление возможности это просто добавление библиотеки

**Comment by sashazernin** [comment]
сейчас сделал саму отправку уведомлений пока не разобрался как уведомления работают, надо создать табличку где будет указаны показанные уведомления.

**Comment by hirurg-lybitel** [comment]
Y

> сейчас сделал саму отправку уведомлений пока не разобрался как уведомления работают, надо создать табличку где будет указаны показанные уведомления.

Не надо никаких табличек создавать.
Если сейчас фронт послыает уведомления в браузер через пуш-уведомления, то этого достаточно

**Comment by hirurg-lybitel** [comment]
Добавил включение/отвключение уведомдений и провверку настроек браузера
