### ISSUE TITLE
Окно создания 2FA

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#425]
На маленьких экранах вся информация не влазит в окно и появлется сролл. 
Например, за счёт адаптивного уменьшения размера qr-кода, вместить всю информацию в окно хотя бы до разрешения 1366х768

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/d6951d21-0044-4ab5-bace-b40ba9545dfa)

**Comment by sashazernin** [comment]
У меня не получилось открыть этот попап и я не понимаю в чем проблема скрола если уменьшить QR то будет не удобно его сканировать.

**Comment by hirurg-lybitel** [comment]
> У меня не получилось открыть этот попап и я не понимаю в чем проблема скрола если уменьшить QR то будет не удобно его сканировать.

что конкретно не получилось?
