### ISSUE TITLE
Приоритет операций не понятен пользователю

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-nxt#430]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/5175764/08aa2b45-d82d-4b72-93ab-4438938c6722)

что будет, если переключатели будут установлены так (сверху вниз):

И
ИЛИ
И

?

**Comment by hirurg-lybitel** [comment]
Так приоритета нет. Они же не связаны между собой. 
Например, выбранные отделы: показать клиентов, которые имеют отдел 1 И отдел 2. 
Лиюо же показать клиентов, у которых ИЛИ отдел 1 ИЛИ отдел 2
