### ISSUE TITLE
Формирование эталонной бд для системы

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#442]
Сюда будем кидать все ошибки и замечания, пока не сформируем рабочий эталон

**Comment by hirurg-lybitel** [comment]
Нужно ли добавить в срм возможность заполнять справочник бизнес-процессов?

**Comment by hjamesgs** [comment]
"Нужно ли добавить в срм возможность заполнять справочник бизнес-процессов?"

**Comment by hjamesgs** [comment]
> @hjamesgs Нужно ли добавить в срм возможность заполнять справочник бизнес-процессов?

Не надо.

**Comment by hirurg-lybitel** [comment]
@hjamesgs 

Рабочая база подключена к срм. 
Теперь надо необходимые данные перегнать из существующих таблиц в наши.
