### ISSUE TITLE
Задачи. Поле Описание сделать не обязательным

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#446]
Задачи. 
1. Поле "Описание"  сделать не обязательным
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/dd9ca591-2b5e-4319-9ee1-82d6fcc81cde)

2. Убрать поля Дата и время выполнения. тк их всё равно нельзя заполнять

3. "Сжать" строчки, чтобы отображались все поля на экран. сейчас все поля на экран поместились, когда в браузере поставил  масштаб 65%.
 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/c3e3f27b-4525-418b-9373-b80ffd99a7d7)

**Comment by sashazernin** [comment]
> 1. Поле "Описание"  сделать не обязательным
>    ![image](https://user-images.githubusercontent.com/11534388/279707467-dd9ca591-2b5e-4319-9ee1-82d6fcc81cde.png)

Тогда можно будет полностью пустую задачу создать
![Uploading image.png…]()

**Comment by hjamesgs** [comment]
"Тогда можно будет полностью пустую задачу создать"

Ну пусть пока будет так.

**Comment by hirurg-lybitel** [comment]
Единный минимизированный стиль для всех полей ввода
