### ISSUE TITLE
Задачи. Добавление

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#447]
При добавлении новой Задачи необходимо сохранить Сделку

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/db1d8ac6-aaf5-4cd6-83c4-0f5804ba9adf)

Надо добавить проверку, если Сделка уже создана, чтобы задача сохранялась.

**Comment by hirurg-lybitel** [comment]
> При добавлении новой Задачи необходимо сохранить Сделку
> 
> ![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/db1d8ac6-aaf5-4cd6-83c4-0f5804ba9adf)
> 
> Надо добавить проверку, если Сделка уже создана, чтобы задача сохранялась.

Не хотят нажать кнопку сохранить а сделке?

**Comment by sashazernin** [comment]
> > При добавлении новой Задачи необходимо сохранить Сделку
> > ![image](https://user-images.githubusercontent.com/11534388/279710265-db1d8ac6-aaf5-4cd6-83c4-0f5804ba9adf.png)
> > Надо добавить проверку, если Сделка уже создана, чтобы задача сохранялась.
> 
> Не хотят нажать кнопку сохранить а сделке?

да думаю в любом случае автосохранение при добавлении задачи удобнее

**Comment by hirurg-lybitel** [comment]
Добавлена обработка в случае, если сделка открывается не через карточку, а через список

**Comment by hjamesgs** [comment]
У меня задача не сохранилась. Задачу сохранил, она отобразилась.
в Сделке нажал "Отмена"

**Comment by hjamesgs** [comment]
Чуть не так. Задача по итогу сохранилась, но в Сделке она не отображается до тех пока, пока не перешел на страницу Задачи, а потом назад на страницу Сделки. только после этого обновилось кол-во и появились задачи.

**Comment by sashazernin** [comment]
> Чуть не так. Задача по итогу сохранилась, но в Сделке она не отображается до тех пока, пока не перешел на страницу Задачи, а потом назад на страницу Сделки. только после этого обновилось кол-во и появились задачи.

задача появляется без переходов, просто задержка из-за ожидания ответа от сервера.
