### ISSUE TITLE
Права просмотра Сделки.

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#448]
Сделку должны видеть все пользователи, которые указаны в задачах по данной сделке
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/71a4cb57-f5ba-4c7c-9528-97b6bf1eae85)

**Comment by sashazernin** [comment]
Сделки видят: создатель и исполнитель сделки, создатели и исполнители задач

**Comment by hirurg-lybitel** [comment]
Добавлена доступность "глазка" для оговоренных пользователей + пользователи, у которых ест право видеть все сделки
