### ISSUE TITLE
Добавить возможность редактирования реквизитов Клиента  из Сделки

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#449]
Добавить возможность редактирования реквизитов Клиента  из Сделки
Типа кнопку Карандаш
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/5e7a4c35-427e-4309-948b-63b4061cdfb2)

**Comment by sashazernin** [comment]
о каких реквизитах идет речь? Вроде клиента и так редактировать можно.

**Comment by hjamesgs** [comment]
чтобы было вот такое окно
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/aecf8698-ff48-4b7d-b1cb-5dc84e7bac8a)

клиент из Сделке по "ручке" не открывается. а вываливается весь список клиентов

**Comment by sashazernin** [comment]
так она есть

https://github.com/gsbelarus/gdmn-nxt/assets/94962537/efd4711a-10a4-4898-9399-c858897e007f

**Comment by hjamesgs** [comment]
Да. Кнопка  есть, но тут нюанс. обрати внимание. какой клиент в Сделке, и какого клиента ты редактируешь.

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/79452bff-b056-4ccc-9cf0-8d174aa6c624)

![Uploading image.png…]()

**Comment by sashazernin** [comment]
> Да. Кнопка есть, но тут нюанс. обрати внимание. какой клиент в Сделке, и какого клиента ты редактируешь.
> 
> ![image](https://user-images.githubusercontent.com/11534388/283718833-79452bff-b056-4ccc-9cf0-8d174aa6c624.png)
> 
> ![image](https://user-images.githubusercontent.com/11534388/283719982-7be49189-cc98-4850-9778-93f18f2c6e56.png)

когда клиента выбираешь для редактирования он в сделке выбирается

**Comment by hjamesgs** [comment]
Я зашел в старую Сделку и хочу отредактировать клиента. Надо сделать кнопку - редактирование текущего клиента. А не выбирать клиента из списка.

**Comment by hjamesgs** [comment]
Окно с реквизитами открывается, но внесенные данные не сохраняются.
