### ISSUE TITLE
Добавить новых 2 этапа для Сделки

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#450]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11534388/d30fa9a3-c52c-4a3b-a80e-f89ed5d7a022)

Добавить кнопку Архив(Выполненные)
по нажатию отображать 2 этапа . Отказ и Завершенные. 

Отказ -  с признаком "Отказ"

**Comment by hirurg-lybitel** [comment]
Добавлен этап Отказ и пункт Выполненные в фильтре

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/5f0d8266-f79e-4e5b-92c2-5cd332e9c03d)

**Comment by hjamesgs** [comment]
Сделки с галочкой "Отказ" не отображаются
