### ISSUE TITLE
Задачи. Список. Редактировать

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#461]
При открытии окана редактирования задачи через список вываливается ошибка 

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/2d22451b-c2f7-4c53-9113-bfbdd7576e45)

**Comment by sashazernin** [comment]
это на какой ветке?

**Comment by hirurg-lybitel** [comment]
в главной

**Comment by sashazernin** [comment]
> в главной

у меня ошибки такой нету

**Comment by hirurg-lybitel** [comment]
Уж не в продакшене открываешь ли?

**Comment by sashazernin** [comment]
https://github.com/gsbelarus/gdmn-nxt/assets/94962537/2d94f49c-27c0-4f63-9f0b-370391f2f26b

**Comment by sashazernin** [comment]
> Читай описание ишью Речь о режиме просмотра через список


https://github.com/gsbelarus/gdmn-nxt/assets/94962537/71d3f18e-1ce0-46a5-a596-c174a5447451

**Comment by hirurg-lybitel** [comment]
> > Читай описание ишью Речь о режиме просмотра через список
> 
>  bandicam.2023-12-22.18-21-10-925.mp4

о чём это видео?
тут нет консоли

**Comment by sashazernin** [comment]
> > > Читай описание ишью Речь о режиме просмотра через список
> > 
> > 
> > bandicam.2023-12-22.18-21-10-925.mp4
> 
> о чём это видео? тут нет консоли

если бы эта ошибка выскакивала то и без консоли ее видно было бы

**Comment by hirurg-lybitel** [comment]
Добавь описание на две строки

**Comment by sashazernin** [comment]
> Попробуй добавить описание на две строки, сохранить, а потом заново открыть

появилось
