### ISSUE TITLE
QR. Бесконечный запрос 

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#462]
Профиль -> безопасность -> Двухфакторная аутентификация

В продакшене (на офисной тестовой версии) при попытке активировать 2fa зависает запрос 

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/29f69b07-0678-4da6-91a8-ba5abeb0dcc3)

**Comment by sashazernin** [comment]
не могу зайти ни к одну учетную запись на продакшене

**Comment by hirurg-lybitel** [comment]
Тогда локально у себя разверни.
Подключили срм к нашей действующей рабочей базе, поэтому доступ ограничен

**Comment by sashazernin** [comment]
у меня все ок, на проекте запущенном через prod

**Comment by hirurg-lybitel** [comment]
А email пользователя задан?
Если да, то удали его

**Comment by sashazernin** [comment]
я так понимаю ты уже поправил это

**Comment by hirurg-lybitel** [comment]
Нет, ишью же открыто

**Comment by sashazernin** [comment]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/8d786426-9ce0-4ad8-ac82-1e672cfbbe5e)
 а это что? и у меня работать начало как надо

**Comment by hirurg-lybitel** [comment]
Это другие баги. Если побочно ещё и эту проблему решило, то замечательно
