### ISSUE TITLE
Пути

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#470]
Сейчас в продакшене с докером обращение к клиентской и серверной части происходит по доменному имени без портов. Между собой общаются тем же способом.

Но локально в деве приходится использовать пути с портами.

В итоге при переключении режимов надо менять код, чтобы всё работало, т.е. по сути существует две параллельные версии программы.

![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/b68fc68e-3897-45c0-87ef-fbdcc664491a)
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/f57a587b-b2ea-4914-b9ba-0573d3b9cc11)

Надо придумать какой-то динамический способ переключения или иное автоматическое решение, чтобы не делать никаких манипуляций в коде

**Comment by sashazernin** [comment]
можно сделать что то вроде этого const origin = process.env.VERSION ? `https://${host}:${appPort}` : `https://${host}`;

**Comment by hirurg-lybitel** [comment]
так ты сам же говоришь, что не будет работать продакшн локально

**Comment by sashazernin** [comment]
> так ты сам же говоришь, что не будет работать продакшн локально

ну просто зачем продакш локально запускать все же а деве делаем

**Comment by sashazernin** [comment]
можно второй вариант сделать

**Comment by hirurg-lybitel** [comment]
> так ты сам же говоришь, что не будет работать продакшн локально

в смысле зачем?
чтобы запустить рабочую версию проекта у клиента без докера

**Comment by hirurg-lybitel** [comment]
> можно второй вариант сделать

как-то это неэлегантно что ли делать отдельные скрипты под каждую задачу. Подумаем ещё над параметризирование
