### ISSUE TITLE
MUI 5 -> 6

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#475]
Изучить возможность перехода на шестую версию библиотеки.
Прочитать гайд и если всё хорошо, осуществить переход так, чтобы ничего не сломалось

**Comment by sashazernin** [comment]
> уже две недели прошло, как успехи?

ну там все еще ругается не знаю как это исправить, гугли но что то найти ничего не могу

**Comment by hirurg-lybitel** [comment]
Хорошо. Ждём обновлений по ишью

**Comment by hirurg-lybitel** [comment]
@sashazernin 
после успешного обновления версии и исправления багов, заменить все компоненты с вводом периода, на новый

**Comment by sashazernin** [comment]
> @sashazernin после успешного обновления версии и исправления багов, заменить все компоненты с вводом периода, на новый

а что на что именно надо заменить?
