### ISSUE TITLE
Мессендежры. Префиксы для ссылок

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#487]
В компонент выбора мессенджера и никнейма добавить объект с префиксами ссылок дял перехода в соответсвующее приложение.

Например, для перехода в telegram чат надо вызвать ссылку `https://t.me/username`.
Таким образом искомый объект должен вернуть для типа мессенджера telegram строку `https://t.me/`.
И так для всех мессендежров, для которых это возможно

**Comment by sashazernin** [comment]
кстати вайбер ватсап там по номеру ищутся контакты, можно стоит разделить на 2 типа nicname и phone и сделать поле для номера.
