### ISSUE TITLE
Контакты. Метки

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#491]
Сейчас метки в контактах отображаются следующим образом:
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/59bc9665-dd8b-4a44-a1c5-c24887d0c3b5)

Сделать так, все метки отображались в строку, сколько влезет, потом с новой строки и так далее:
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/9abb1609-1f78-4537-9faa-eca830e234bf)

**Comment by sashazernin** [comment]
Подскажи как можно лучше просчитать высоту для строки? думаю сделать через getRowHeight

**Comment by hirurg-lybitel** [comment]
> Подскажи как можно лучше просчитать высоту для строки? думаю сделать через getRowHeight

думаю, её не надо вовсе просчитывать, а настроить, чтобы растягивалась высотак у каждой строки.
В документации есть соотвествующий раздел про динамическую выоту
