### ISSUE TITLE
Клиенты. Контакты

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#492]
Сейчас в клиентах можно только создаввать контакты.
Надо добавить возможность выбирать существующих.

Т.е. должен при нажатии на какую-то кнопку появляться выпадающий список с выбором одного или нескольких контактов. 
После подтверждения выбора выбранные контакты появляются в списке контактов клиента.

**Comment by hirurg-lybitel** [comment]
Почему задача помеченная как сделанная? Не видел ни пул реквестов, никакой другой информации

**Comment by sashazernin** [comment]
> Почему задача помеченная как сделанная? Не видел ни пул реквестов, никакой другой информации

видимо случайно переместил в done а не в впроцессе
