### ISSUE TITLE
Контакты. Редактирование

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#495]
При редактировании записи открывается инпут и если их несколько, то инпуты накладываются друг на друга. 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/4436e573-b866-4262-bcfe-fcd27d2ee75b)

Сделать так, чтобы при открытом инпуте при нажатии за область всего компонента (инпут + кнопки) режим редактирования заканчивался и инпут закрывался

**Comment by sashazernin** [comment]
![image](https://github.com/gsbelarus/gdmn-nxt/assets/94962537/cd3ea5cb-e588-4334-a938-1bfe5fc684f5)
я бы еще сделал, при прекращении редактирования если поле пустое удалять его а не оставлять таким.

**Comment by sashazernin** [comment]
а еще во время редактирования поле имеется озможность перейти по ссылке нажав на пространство между кнопками и само пространство cursor: pointer. я бы тоже это пофиксил

**Comment by hirurg-lybitel** [comment]
> ![image](https://private-user-images.githubusercontent.com/94962537/302141582-cd3ea5cb-e588-4334-a938-1bfe5fc684f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDUyMjAsIm5iZiI6MTcwNzE0NDkyMCwicGF0aCI6Ii85NDk2MjUzNy8zMDIxNDE1ODItY2QzZWE1Y2ItZTU4OC00MzM0LWE5MzgtMWJmZTVmYzY4NGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE0NTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YTIxM2IxMDAyN2EzYmVhYWYwNGIzNjVjNWY3MGQ2ZGQwYmU5YTBlZGZiMjI4NTU1YWQzNjY2MDNiMWMxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0ZzuoW34jSVCDy-WsXzYizh8k5Hgwfng-OgshzhEKY) я бы еще сделал, при прекращении редактирования если поле пустое удалять его а не оставлять таким. Так же, во время редактирования, поля, имеется возможность перейти по ссылке, нажав на пространство между кнопками. И само пространство cursor: pointer. я бы тоже это пофиксил.

Хорошо, фикси
