### ISSUE TITLE
Высота строки

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#521]
Не заметил сразу

Когда имеем длинный список меток, всё хорошо переносится, но если имеем одну и переносить ничего не надо, то высота строки всё равно меняется. 
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/ffb91b87-3ebf-4786-81da-743f6408173c)

Однострочные данные должны быть одного размера. У нас это 40px сейчас

**Comment by sashazernin** [comment]
получается надо как то узнавать влазят ли эти метки в строку без переноса, как можно лучше это сделать? мне в голову пришло только получать элемент с метками и проверять есть ли перенос у него, но мне кажется такая себе идея

**Comment by hirurg-lybitel** [comment]
Почему закрыл? Я никаких доработок по этому ишью не видел

**Comment by sashazernin** [comment]
> @sashazernin Почему закрыл? Я никаких доработок или пулреквестов по этому ишью не видел

вроде же смерджили решение в мейн

**Comment by hirurg-lybitel** [comment]
каким пулреквестом?

**Comment by sashazernin** [comment]
забыл реквест кинуть
