### ISSUE TITLE
Строка поиска. Ширина инпута 

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#541]
Инпут не на весь компонент
![image](https://github.com/gsbelarus/gdmn-nxt/assets/11502258/6450ff4e-111c-405d-b87e-d32f400fe2bd)

**Comment by sashazernin** [comment]
а где этот импут?

**Comment by hirurg-lybitel** [comment]
В шапке справочника Контакты, например
