### ISSUE TITLE
Настройки. Вкладки

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#546]
Активная (текущая) вкладка не подсвечивается, как по умолчанию должна в данном компоненте. Посмотреть, что сломалось

**Comment by sashazernin** [comment]
я бы убрал переключение пути, или это обязательно так должно быть?

**Comment by hirurg-lybitel** [comment]
> потому что эта вкладка относится к конкретному пути, а при переключении путь меняется.

и как это связано с цветом текущей вкладки?

**Comment by hirurg-lybitel** [comment]
> я бы убрал смену пути при переключении, или это обязательно так должно быть?

твой вариант открывать конкретную вкладку при переходе по ссылке?

Например, где-то на другой странице хотим сказать пользователю, чтобы он включил что-нибудь в настройках уведомлений и предложить ему ссылку для быстрого перехода

**Comment by sashazernin** [comment]
> > потому что эта вкладка относится к конкретному пути, а при переключении путь меняется.
> 
> и как это связано с цветом текущей вкладки?

кнопка имеет статус isActive при открытой ссылке к который кнопка ссылается, а тут при переключении открывается другая ссылка.

**Comment by hirurg-lybitel** [comment]
> > > потому что эта вкладка относится к конкретному пути, а при переключении путь меняется.
> > 
> > 
> > и как это связано с цветом текущей вкладки?
> 
> кнопка имеет статус isActive при открытой ссылке к который кнопка ссылается, а тут при переключении открывается другая ссылка. Поэтому она теряет статус isActive

Так и в чём проблема? 
Исходя из написанного, другая вкладка должна становиться активной и, соответсвенно, синей
