### ISSUE TITLE
Реквизиты клиента

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#63]
https://github.com/gsbelarus/gdmn-nxt/issues/41 

Трубуется создать справочник ответсвенных лиц. Каждому клиенту может соответсвовать много лиц.

Поля для них:
-  Для какого отдела
-  ФИО 1 сотрудника(клиента)  
-  Тел.раб. 
-  Тел.моб.
-  E-mail
-  Доверенность  
-  Должность
-  Комментарий
-  Адрес

**Comment by hirurg-lybitel** [comment]
@hjamesgs проверка

**Comment by hjamesgs** [comment]
Доверенность - текстовое поле (80-100 символов должно хватить). "№ от Даты"

**Comment by hirurg-lybitel** [comment]
@hjamesgs  Получилась такая реализация:

![image](https://user-images.githubusercontent.com/11502258/161569977-41040e50-c2d2-4b65-955d-1587e1be8f16.png)
![image](https://user-images.githubusercontent.com/11502258/161570009-ab58283f-b6de-4d5c-8625-6c547b1350c0.png)

**Comment by hjamesgs** [comment]
В реквизитах организации добавить 
1. УНП
2. Адрес юридической

В нижней части, где информация о Контактах добавить для отображение поле Отдел, т.е. 3 колонки должно быть

**Comment by hjamesgs** [comment]
1.	«Контакты» переименовать в «Сотрудники клиента»
![image](https://user-images.githubusercontent.com/11534388/184926186-e59e3814-671e-4a39-b20c-02caece54436.png)

2.	Возможность Просмотр информации по клиенту без редактирования
