### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-nxt#73]
Заказчику надо презентовать что-то полноценное, рабочее в плане справочника клиентов и минимума полезной функциональности. Я бы подумал о следующем:

1. Полноценная работа со справочником контактов. Отображение, фильтрация, сортировка, создание, изменение, удаление записей со всеми полями, а не только некоторыми. Включая редактирование списка лэйблов и присвоение их клиентам.
2. Сразу возникнет вопрос с объемами передаваемой информации. Тут может быть несколько решений:
    1. Вводим ограничение на стороне сервера. Например, максимум 2000 записей. Если запрос больше возвращает, то их не считываем, а на клиента пересылаем флаг. Пользователю сообщаем, что это не все данные и ему следует ограничить условия выборки. При этом надо дать возможность пользователю на клиенте задавать фильтр, который потом идет в SQL запрос.
    2. Предусмотреть pagination когда на клиент передается только ограниченное окно с данными от общей выборки. При этом можно перемещаться по всей выборке. Нужные данные при этом подгружаются с сервера, ненужные -- высвобождаются.
    3. Лезть в дебри драйвера и передавать не JSON объекты, а двоичный буфер. Соответственно и хранить данные на клиенте не JS объектами, а двоичным буфером, вытаскивая из него и формируя только те объекты, которые нужны для отображения в реакте. По идее это в несколько раз уменьшит требования к памяти.
3. Добавить ABC анализ списка клиентов: по объему выручки, по оплатам, по задолженностям. В разрезе географических областей, видов деятельности и т.п.
4. Посмотреть, сможем ли мы вывести карту с отображением клиентов (кластеров клиентов) на карте. Чтобы наглядно было видно в каких областях лучше идет продажа, в каких хуже и т.п.

Режим для клиента.

Сейчас в этом режиме у нас только акт сверки. Надо проверить весь техпроцесс:

1. Клиент регистрируется. Его запись в неподтвержденном состоянии.
2. Сотрудник белгисса авторизует запись.
3. Клиент может входить под своей учетной записью и просматривать акт сверки.

или предложить другой вариант проверки клиента. например, через выдачу временного пин кода.

**Comment by hirurg-lybitel** [comment]
@hjamesgs

**Comment by gsbelarus** [comment]
Вот док по гугл картам:

https://developers.google.com/maps/documentation/javascript/react-map

**Comment by hirurg-lybitel** [comment]
Делаю карту.

Есть у нас ключ api полноценный?
Я как понял без билинга урезанный функционал у карт, а для билинга платёжную карточку привзяать надо, но мои не проходят

**Comment by hirurg-lybitel** [comment]
Карта

Для построения маркеров нужны координаты. Определять их динамически из текстового адреса клиента при загрузке карты довольно ресурсоёмко, так что надо подумать, как бы на Гедымине при создании записи получать эти данные. А потом по всему справочнику пробежаться и заполнить.

**Comment by gsbelarus** [comment]
поля с координатами в справочнике контактов есть. адрес есть. простой макрос сделать который пробежит и проставит всем, где не проставлено.

**Comment by hirurg-lybitel** [comment]
Ну так о том и речь, чтобы что-то подключить, что рассчитает координаты по адресу.

**Comment by gsbelarus** [comment]
я не думаю что так уж точно надо координаты. это же не для наведения
крылатых ракет... у нас есть населенный пункт в контакте, мы можем по нему
вывести контакт на карте? не вдаваясь в более детальные координаты.

**Comment by hirurg-lybitel** [comment]
> 

Ещё раз обрисую.

Маркеры строятся по координатам latitude и longitude.

Их можно получить через разлиные api geocode по адресу, но такой api будет работать очень долго для тысяч клиентов, поэтому напрашивается хранение координат в базе и их получение на условном dobeforepost.

Есть альтернативы гуглу без привязки карты, например https://positionstack.com, но там тоже ограничение на количество запросов в месяц

**Comment by gsbelarus** [comment]
еще раз говорю, что в gd_contact есть поля для lat, lon. т.е. не надо их
каждый раз получать. их надо брать из бд.
а заносить туда макросом или при сохранении записи.

**Comment by gsbelarus** [comment]
https://excelstore.pro/examples-of-work/internet/get-the-address-and-coordinates-of-yandex-and-google.html

**Comment by gsbelarus** [comment]
https://connect.smartliving.ru/profile/2594/blog/poluchenie-adresa-po-koordinatam.html

можно яндекс попробовать вместо гугла.

но, вообще, если такие сложности вызывает то лучше бросить пока

**Comment by hirurg-lybitel** [comment]
Суть в том, что бесплатно никто не предоставляет неорганиченно эту функцию, тут даже можно не шерстить интернет, так что надо как-то встраивать в стоимость продукта.
Гугл нам в принципе недоступен на бел резидентство, а яндекс морально спонсировать неприятно быть должно.

Есть другие сервисы, которые я выше описал, но там даже на уровне тестирования бесплатный лимит иссякнет

**Comment by hjamesgs** [comment]
а расскажите, про п.4.
зачем на карте рисовать точки, где находятся клиенты? какой смысл в этом?

**Comment by hirurg-lybitel** [comment]
> а расскажите, про п.4. зачем на карте рисовать точки, где находятся клиенты? какой смысл в этом?

@gsbelarus

**Comment by gsbelarus** [comment]
исключительно ради красоты. картинку директору создать.

пт, 20 мая 2022, 03:24 карыстальнік hirurg-lybitel ***@***.***>
напісаў:
