### ISSUE TITLE
Фильтрация клиентов

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#77]
- [x] добавить возможность выбора метода фильтрации И/ИЛИ
- [x] сохранять фильтр при выходе из режима детализации по клиенту
- [x] Добавить фильтрацию по Видам работ

**Comment by hjamesgs** [comment]
- [ ] Добавить фильтрацию по Видам работ

Вид работ связан со справочником заказов

select
  w.USR$NAME
from
  USR$BG_JOBWORK w
where
  w.USR$CONTRACTJOBKEY in (:id)
  and coalesce(w.USR$NOTACTIVE,1) = 0
