### ISSUE TITLE
Работа с клиентом

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#78]
- [x] Отображение текущего клиента
- [x] Отдельный справочник для меток с возможностью их создания 
- [x] Не обновлять список клиентов при возвращении в главное окно

**Comment by hjamesgs** [comment]
"Не обновлять список клиентов при возвращении в главное окно"

После редактирования и сохранения клиента «перегружается» весь список. Очень долго 40+ сек.
