### ISSUE TITLE
Сделки

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#80]
- [x] Добавить поля срок, исполнитель, кто создал, источинк (сайт, звонок и т.п.)
- [x] Автоматическое создание новой сделки в Заявка ИЦ-26
- [x] Добавить возможность копированя сделки, как  в Гедымине.
- [x] Проверить удаление.
- [x] Шаблоны прав для отделов
- [x] Шаблоны этапов сделок

**Comment by hjamesgs** [comment]
Добавить Справочник этапов сделок.
Из этого справочника можно будет создавать Шаблон (с перечисленными этапами) и дальше его использовать для пользователя (подразделения)

**Comment by hjamesgs** [comment]
в Сделке
1.	Добавить «Отдел»
2.	Добавить галочку «Отказ»
3.	Справочник «Отказов» + текстовое поле «Комментарий»
4.	Поле «Источник» переделать на Справочник
 
![image](https://user-images.githubusercontent.com/11534388/184912395-957333e8-a4c4-410b-bce2-22371798e6be.png)

**Comment by hirurg-lybitel** [comment]
> в Сделке
> 
> 1. Добавить «Отдел»
> 2. Добавить галочку «Отказ»
> 3. Справочник «Отказов» + текстовое поле «Комментарий»
> 4. Поле «Источник» переделать на Справочник
> 
> ![image](https://user-images.githubusercontent.com/11534388/184912395-957333e8-a4c4-410b-bce2-22371798e6be.png)

1 Выбор отдела вместо выбора исполнителя?
2 О чём должна свидетельствовать установленная галочка Отказ?
3 Что за справочник отказов?
4 Какой-то существующий справочник? Если нет, то что в нём должно быть?

**Comment by hjamesgs** [comment]
1 Выбор отдела вместо выбора исполнителя?
  Новое поле- ссылка на Отдел
2 О чём должна свидетельствовать установленная галочка Отказ?
  Отказ - это отказ клиента от проведения работ  и т.п.
3 Что за справочник отказов?
4 Какой-то существующий справочник? Если нет, то что в нём должно быть?
  Новый справочник. Доступ из Гедымина.

**Comment by hirurg-lybitel** [comment]
> 1 Выбор отдела вместо выбора исполнителя? Новое поле- ссылка на Отдел 2 О чём должна свидетельствовать установленная галочка Отказ? Отказ - это отказ клиента от проведения работ и т.п. 3 Что за справочник отказов? 4 Какой-то существующий справочник? Если нет, то что в нём должно быть? Новый справочник. Доступ из Гедымина.

> Отказ - это отказ клиента от проведения работ и т.п.
И что происходит с такой сделкой? В какой этап она попадает?

**Comment by hjamesgs** [comment]
Отказ  - сделка проходит все этапы (чтобы не ломать логику) и на последнем этапе (Исполнено) устанавливается этот признак и из справочника указывается причина. 
Примеры причин отказа:
-Мониторинг цен
-Вне компетенции
-Высокая стоимость
-Сроки
и т.п
Другое (пишем причину). Должно быть текстовое поле с комментарием.

**Comment by hjamesgs** [comment]
Добавить в Сделку дополнительные поля :
- № заявки (20 символов)
- Наименование продукции (180 символов)
- ФИО (кто обратился)
- Email
- Телефон

**Comment by hirurg-lybitel** [comment]
Не надо переоткрывать, пожалуйста, закрытые issue. Пиши новые

> Добавить в Сделку дополнительные поля :
> 
> * № заявки (20 символов)
> * Наименование продукции (180 символов)
> * ФИО (кто обратился)
> * Email
> * Телефон
