### ISSUE TITLE
Отчёт по остаткам

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#81]
![image](https://user-images.githubusercontent.com/11502258/172625925-0cfc8ddb-ffc5-4f46-a520-8a08c40c1b7a.png)

запрос ждём...

**Comment by hjamesgs** [comment]
select
  a.ALIAS,
  a.ID,
  a.name,
  curr.CODE,
  sum(e.DEBITNCU - e.CREDITNCU) as SaldoCurr
from
  ac_entry e
  join ac_account a on a.id = e.ACCOUNTKEY
  join GD_CURR curr on curr.ID = e.CURRKEY
where
  e.ENTRYDATE <= :ForDate and
  a.id in (355100, 338278175, 329437051, 353235866, 353938398)
group by
  1,2,3,4
 having
  sum(e.DEBITNCU - e.CREDITNCU) > 0

union all

select
  a.ALIAS,
  a.ID,
  a.name,
  curr.CODE,
  sum(e.DEBITCURR - e.CREDITCURR) as SaldoCurr
from
  ac_entry e
  join ac_account a on a.id = e.ACCOUNTKEY
  join GD_CURR curr on curr.ID = e.CURRKEY
where
  e.ENTRYDATE <= :ForDate  and curr.id <> 200010 and
 a.id in (355201, 355202, 148348896, 338061063, 353235817, 353235818, 353235819, 353938400, 353938401, 353938402)
group by
  1,2, 3, 4
 having  sum(e.DEBITCURR - e.CREDITCURR) > 0
order by
  3

**Comment by hirurg-lybitel** [comment]
![image](https://user-images.githubusercontent.com/11502258/175432410-06cf0644-3e96-46e8-bd7c-51004ac9894a.png)
