### ISSUE TITLE
Перенести все фильтры списка клиентов на график продаж

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#87]

**Comment by hjamesgs** [comment]
1. Исправить заглавие закладки. Вместо «Продажи за месяц» на «Продажи за Период» 
2. Заказы отображать в выпадающем списке "Заказы"
3. Добавить фильтрацию для ячейки «Виды  работ» (так же как и в «Списке клиентов»)
