### ISSUE TITLE
Новый Отчет – Топ 10 -  20  - 50    по Выручке

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#95]
Новый Отчет – Топ 10 -  20  - 50    по Выручке по отделам (возможность выбрать несколько отделов) за период

**Comment by hirurg-lybitel** [comment]
@hjamesgs  запросик бы, пожалуйста

**Comment by hjamesgs** [comment]
Параметры для построения отчета "Дата начала" - "Дата окончания"
В шапке стандартная фильтрация "Подразделение" "Заказ" "Вид работ"

SELECT   first(:CountCustomer)
  con.name,
  con.id,
  SUM(c.USR$SUMNCU)
FROM
  USR$CRM_CUSTOMER c
  join gd_contact con on con.ID = c.USR$CUSTOMERKEY
where
  c.USR$DOCDATE >= :datebegin and
  c.USR$DOCDATE <= :dateend
  and c.USR$DEPOTKEY = :depID
  and c.USR$JOBKEY = :JOBID
  and c.USR$JOBWORKKEY = :JOBWorkID

group by
  con.name,
  con.id
order by 3 desc


:CountCustomer   10, 20 или 50. Ограничимся такими значениями в выборе параметров

**Comment by hjamesgs** [comment]
По подразделениям несколько вариантов. Всё остальное одиночный выбор.

**Comment by hirurg-lybitel** [comment]
пока такой вариант 
![image](https://user-images.githubusercontent.com/11502258/188003662-2f091f08-cb8e-4503-b28c-583804c62160.png)
