### ISSUE TITLE
Не работает «глазик» и не отображается на маленьких мониторах

### ISSUE THREAD

**Issue by hirurg-lybitel** [gsbelarus/gdmn-nxt#98]
Не работает «глазик» и не отображается на маленьких мониторах

![image](https://user-images.githubusercontent.com/11534388/184925863-593b0b74-b821-42c6-b6fb-6fe3bf1ca276.png)

_Originally posted by @hjamesgs in https://github.com/gsbelarus/gdmn-nxt/issues/41#issuecomment-1216839901_

**Comment by hirurg-lybitel** [comment]
Что значит не работает? Не открывается ничего при нажатии?

А можно пример разрешения маленького экрана?

**Comment by gsbelarus** [comment]
открой дев тулз в браузере. ф12. там можно переключать и смотреть как страница будет выглядеть на разных разрешениях и разных устройствах.

**Comment by hjamesgs** [comment]
На глазик нажимаешь - ничего не происходит
На принскрине видно, что названий организаций не видно. снизу бегунок.
