### ISSUE TITLE
Клиенты. При нажатии на "глазок" (просмотр карточки клиента)

### ISSUE THREAD

**Issue by hjamesgs** [gsbelarus/gdmn-nxt#99]
На Закладку "Реквизиты"

![image](https://user-images.githubusercontent.com/11534388/187857800-72393678-5cd8-4c7c-9493-114ad708cc81.png)

Наименование
УНП
Емайл
Телефон
Адрес
(сведения по сотрудникам)
ФИО1 Должность1 телефон1 емайл1 отдел1
ФИО2 Должность2 телефон2 емайл2 отдел2
...

Добавить закладку "Сделки"
В ней отобразить сделки по выбранному клиенту
Наименование, Сумма, Подразделение, Срок, Статус (в работе, исполненн и тп)

**Comment by hjamesgs** [comment]
На Закладке "Подробно" отобразить следующие поля:
Наименование клиента полное
наименование клиента краткое
УНП
Адрес юридический
Адрес почтовый
Телефон
Факс
E-mail
Доп Информация текстом (Запрос добавлю)

**Comment by hirurg-lybitel** [comment]
Добавить виды работ в Акты выполненных работ
